name: Build with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Light-Works-Linux-x86_64'
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Light-Works-Windows-x86_64'