name: Build with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.3'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Light-Works-Linux'