name: Build with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Light-Works-Linux'